import { Manrope } from "next/font/google"

import type { Metadata } from "next"

import "./globals.css"

import Providers from "./providers"

const manrope = Manrope({
  variable: "--font-manrope",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
