import { Manrope } from "next/font/google"

import type { Metadata } from "next"

import "./globals.css"

import { Navbar } from "@/components/Navbar"

import Providers from "./providers"

const manrope = Manrope({
  variable: "--font-manrope",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        <Providers>
          <Navbar />
          <main className="max-w-6xl w-full mx-auto py-10 px-6">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
